# Generated by Django 3.1.1 on 2020-10-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userextensionmodel',
            table='UserExtensionModel',
        ),
    ]
