# Generated by Django 3.1.1 on 2020-10-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20201007_1859'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userextensionmodel',
            table='user_extension_model',
        ),
    ]
