# Generated by Django 3.1.1 on 2020-09-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('emoji', models.TextField()),
                ('likes', models.PositiveIntegerField()),
                ('search_term', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterJSON',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Twitter_data',
            fields=[
                ('keyData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FrontEnd_Twitter.data')),
                ('is_retweet', models.CharField(max_length=5)),
                ('is_thread', models.CharField(max_length=5)),
                ('media', models.TextField()),
                ('retweets', models.TextField()),
                ('related_hashtags', models.TextField()),
                ('external_links', models.TextField()),
                ('tweet_link', models.TextField()),
            ],
        ),
    ]
