# Generated by Django 3.1.1 on 2020-10-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd_Twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='Data',
        ),
        migrations.AlterModelTable(
            name='twitter_data',
            table='Twitter_Data',
        ),
        migrations.AlterModelTable(
            name='twitterjson',
            table='Twitter_JSON',
        ),
    ]
