# Generated by Django 3.1.1 on 2020-09-21 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd_Twitter', '0002_userextensionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtensionModel',
        ),
    ]
