# Generated by Django 3.1.1 on 2020-10-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd_Twitter', '0002_auto_20201007_1859'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
        migrations.AlterModelTable(
            name='twitter_data',
            table='twitter_data',
        ),
        migrations.AlterModelTable(
            name='twitterjson',
            table='twitter_json',
        ),
    ]
