# Generated by Django 2.0.13 on 2020-09-10 06:54

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterJSON',
            fields=[
                ('_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('json', djongo.models.fields.JSONField()),
            ],
        ),
    ]
