# Generated by Django 2.0.13 on 2020-09-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_twitterjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='emoji',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='search_term',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='twitter_data',
            name='media',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='twitter_data',
            name='related_hashtags',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='twitter_data',
            name='retweets',
            field=models.CharField(max_length=50),
        ),
    ]
